name: Upload config files to account specific S3 buckets

on:
  push:
    branches:
      - main
    paths:
      - "config/osprod/**"
  pull_request:
    paths:
      - 'config/aisdev/**'

env:
  AWS_REGION: "us-east-1"
  AISDEV: "780517085903"
  OSPROD: "947476294539"

permissions:
  id-token: write # This is required for requesting the JWT from AWS
  contents: read  # This is required for actions/checkout

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          dir_names: true
          dir_names_max_depth: 2
          files: |
            config/**

      - name: List all changed files
        run: echo '${{ steps.changed-files.outputs.all_changed_files }}'

      - name: Set environment variables
        id: set-env
        run: |
          SOURCE_DIR="aisdev"
          TARGET_BUCKET=$(basename $SOURCE_DIR)-sre-config
          ACCOUNT_VAR=$(basename $SOURCE_DIR | tr '[:lower:]' '[:upper:]')
          echo $SOURCE_DIR
          echo $TARGET_BUCKET
          echo $ACCOUNT_VAR

